# Generated by Django 4.2.4 on 2023-09-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_category_options_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_due',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сделать до'),
        ),
    ]
