# Generated by Django 4.2.4 on 2023-09-05 16:44

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_task_level_task_lft_task_parent_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todo.task', verbose_name='Вложено в'),
        ),
    ]
